spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/test_db
  liquibase:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'