spring:
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://192.168.0.6:5432/test_db
  liquibase:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'